### ISSUE TITLE
data-load 관련 

### ISSUE THREAD

**Issue by Hyrge** [Jang-Je/OOP-final-assignment#19]
기능 구현하면서 다른 클래스를 너무 심하게 만지느라 data-load 브랜치를 새로 팠어요 
벼락치기로 하는 바람에 구조적인 문제가 심한데 일단 올립니다 .. ㅜㅜ 늦어서 죄송해요 
GameScreen에서 CreatSword와 관련된 것들을 전부 maincontroller로 옮기면 나을 것 같다고 제안드립니다
player 객체가 생성될 때 nowSword를 결정하는 데에 검 리스트에서 찾을 필요가 있는데 이게 GameScreen에 있으니 불편함이 이만저만이 아닙니다 
일단 돌아가기는 하니 data-load 브랜치로 접속하셔서 구현 방향에 대해 결정해주셨음 합니다

**Comment by JangYeongHu** [comment]
괜찮습니다. 제가 너무 급하게 준비해달라고 한 감도 없잖아 있어서요..
그 부분에 대해서는 나중에 같이 얘기 나눠봅시다.
로드 스크린에서 메인 스크린으로 넘어가는 기능은 제가 임시로 추가하겠습니다
